version: '3'

services:
    mongo:
        container_name: mongo
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        ports:
            - "27017:27017"
        networks:
            - common
        restart: always    

    redis:
        container_name: redis
        image: redis:latest
        volumes:
            - redis-data:/data
        ports:
            - "6379:6379"
        networks:
            - common
        restart: always

networks:
    common:

volumes:
    mongo-data:
    redis-data: